#!/usr/bin/env bash
set -euo pipefail

main() {
    local cluster="${BUILDKITE_PLUGIN_ECS_DEPLOY_CLUSTER:-}"
    local service="${BUILDKITE_PLUGIN_ECS_DEPLOY_SERVICE:-}"
    local region="${AWS_DEFAULT_REGION:-${BUILDKITE_PLUGIN_ECS_DEPLOY_REGION:-eu-west-1}}"

    if [[ -n ${cluster} && -n ${service} ]]; then
        echo "--- :ecs: Deploying ${service}"
        aws ecs update-service \
            --cluster "${cluster}" \
            --service "${service}" \
            --force-new-deployment \
            --region "${region}"

        echo "--- :ecs: Waiting for ${service} desired service state"
        aws ecs wait services-stable \
            --cluster "${cluster}" \
            --services "${service}" \
            --region "${region}"

        echo "--- :ecs: Service ${service} is up :rocket:"
    else
        echo >&2 "Missing BUILDKITE_PLUGIN_ECS_DEPLOY_CLUSTER or BUILDKITE_PLUGIN_ECS_DEPLOY_SERVICE"
    fi
}

main
